baseURL = "/"
languageCode = "en-us"
title = "Skyview Stormbots"
theme = "hugo-initio-master"
publishDir = "public"

[params]
    name = ""
    description = ""
    email = ""
    phone = ""
    address = ""
    year = 2018
    background = ""
    favicon = "images/gt_favicon.png"
    DateForm = "January 2, 2006"

    showSubheader = true
    showServices = false
    showRecentWorks = false
    showDownload = false
    showClients = false

    footerEnableContact = false
    footerEnableFollowme = false
    footerEnableTextWidget = false
    footerEnableFormWidget = false

[taxonomies]
  tag = "tags"
  category = "categories"
  season = "seasons"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Partners"
    url = "/partners/"
    weight = 5
    identifier = "partners"
    
[[menu.main]]
    name = "Our Partners"
    url = "/partners/"
    weight = 1
    identifier = "ourpartners"
    parent = "partners"

[[menu.main]]
    name = "Get Involved"
    url = "/get-involved"
    weight = 2
    parent = "partners"

[[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 10

[[menu.main]]
    name = "Games"
    url = "/games/"
    weight = 15
    identifier = "games"

    [[menu.main]]
      name = "Games"
      url = "/games/"
      weight = 14
      parent = "games"

    [[menu.main]]
      name = "FIRST Power Up"
      url = "/power_up/"
      weight = 15
      parent = "games"

      [[menu.main]]
        name = "FIRST Stronghold"
        url = "/stronghold/"
        weight = 16
        parent = "games"

        [[menu.main]]
          name = "FIRST Recycle Rush"
          url = "/recycle_rush/"
          weight = 17
          parent = "games"

          [[menu.main]]
            name = "FIRST Aerial Assist"
            url = "/aerial_assist/"
            weight = 18
            parent = "games"

            [[menu.main]]
              name = "FIRST Ultimate Ascent"
              url = "/ultimate_ascent/"
              weight = 19
              parent = "games"

              [[menu.main]]
                name = "FIRST Rebound Rumble"
                url = "/rebound_rumble/"
                weight = 20
                parent = "games"

                [[menu.main]]
                  name = "FIRST Logomotion"
                  url = "/logomotion/"
                  weight = 21
                  parent = "games"

                  [[menu.main]]
                    name = "FIRST Breakaway"
                    url = "/breakaway/"
                    weight = 22
                    parent = "games"

                    [[menu.main]]
                      name = "FIRST Lunacy"
                      url = "/lunacy/"
                      weight = 23
                      parent = "games"

[[menu.main]]
    name = "Media"
    url = "/media/"
    weight = 20
    identifier = "media"

[[menu.main]]
  name = "Photos"
  url = "/categories/photo"
  weight = 20
  identifier = "photos"
  parent = "media"

[[menu.main]]
  name = "Videos"
  url = "/categories/video"
  weight = 20
  identifier = "videos"
  parent = "media"

[[menu.main]]
    name = "Calendar"
    url = "/calendar/"
    weight = 25

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 30

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 35
