baseURL = "/"
languageCode = "en-us"
title = "Skyview Stormbots"
theme = "hugo-initio-master"
publishDir = "public"

[params]
    name = ""
    description = ""
    email = ""
    phone = ""
    address = ""
    year = 2018
    background = ""
    favicon = "images/gt_favicon.png"
    DateForm = "January 2, 2006"

    showSubheader = true
    showServices = false
    showRecentWorks = false
    showDownload = false
    showClients = false

    footerEnableContact = false
    footerEnableFollowme = false
    footerEnableTextWidget = false
    footerEnableFormWidget = false

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Partners"
    url = "/partners/"
    weight = 5

[[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 10

[[menu.main]]
    name = "Games"
    url = "/games/"
    weight = 15
    identifier = "games"

    [[menu.main]]
      name = "Games"
      url = "/games/"
      weight = 14
      parent = "games"

    [[menu.main]]
      name = "FIRST Power Up"
      url = "/power_up.md"
      weight = 15
      parent = "games"

      [[menu.main]]
        name = "FIRST Stronghold"
        url = "/stronghold.md"
        weight = 16
        parent = "games"

        [[menu.main]]
          name = "FIRST Recycle Rush"
          url = "/recycle_rush.md"
          weight = 17
          parent = "games"

          [[menu.main]]
            name = "FIRST Aerial Assist"
            url = "/aerial_assist.md"
            weight = 18
            parent = "games"

            [[menu.main]]
              name = "FIRST Ultimate Ascent"
              url = "/ultimate_ascent.md"
              weight = 19
              parent = "games"

              [[menu.main]]
                name = "FIRST Rebound Rumble"
                url = "/rebound_rumble.md"
                weight = 20
                parent = "games"

                [[menu.main]]
                  name = "FIRST Logomotion"
                  url = "/logomotion.md"
                  weight = 21
                  parent = "games"

                  [[menu.main]]
                    name = "FIRST Breakaway"
                    url = "/breakaway.md"
                    weight = 22
                    parent = "games"

[[menu.main]]
    name = "Media"
    url = "/media/"
    weight = 20
    identifier = "media"

[[menu.main]]
  name = "Photos"
  url = "/categories/photo"
  weight = 20
  identifier = "photos"
  parent = "media"

[[menu.main]]
  name = "Videos"
  url = "/categories/video"
  weight = 20
  identifier = "videos"
  parent = "media"

[[menu.main]]
    name = "Calendar"
    url = "/calendar/"
    weight = 25

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 30

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 35

[params.disqus]
    site = "hugo-initio-site.disqus.com"

[params.sharethis]
    property = "123456789012345678901234"
    custom = true

[params.google.analytics]
    trackerID = "GA-000000000-0"

[[params.social]]
	title = "facebook"
	url = "https://www.facebook.com/nickname"
    icon = "fa-facebook-square"
    footer = true
    sharethis = true
    network = "facebook"
[[params.social]]
	title = "twitter"
	url = "https://twitter.com/nickname"
    icon = "fa-twitter-square"
    footer = true
    sharethis = true
    network = "twitter"
[[params.social]]
	title = "instagram"
	url = "https://www.instagram.com/nickname"
    icon = "fa-instagram"
    footer = true
    sharethis = false
    network = ""
[[params.social]]
	title = "google+"
	url = "https://plus.google.com/+nickname"
    icon = "fa-google-plus-square"
    footer = false
    sharethis = true
    network = "googleplus"
[[params.social]]
	title = "linkedin"
	url = "https://www.linkedin.com/in/nickname"
    icon = "fa-linkedin-square"
    footer = false
    sharethis = true
    network = "linkedin"
[[params.social]]
	title = "tumblr"
	url = "https://nickname.tumblr.com"
    icon = "fa-tumblr-square"
    footer = false
    sharethis = false
    network = "tumblr"
[[params.social]]
	title = "github"
	url = "https://github.com/nickname"
    icon = "fa-github"
    footer = true
    sharethis = false
    network = ""
[[params.social]]
	title = "email"
	url = "mailto:some.email@somewhere.com"
    icon = "fa-envelope"
    footer = false
    sharethis = true
    network = "email"
