backend:
  name: git-gateway
  branch: feature/netlify
media_folder: "static/images/uploads"
public_folder: "/images/uploads"
collections:
- name: "home"
  label: "Home Page"
  files:
    - name: "home-data"
      label: "Home"
      file: "data/home.yml"
      fields:
        - {label: "Main Header", name: "header1", widget: "string"}
        - {label: "Main Subheader", name: "header2", widget: "string"}
        - {label: "Main Content", name: "main_content", widget: "markdown"}
        - {label: "Secondary Header", name: "secondary_header", widget: "string"}
        - {label: "Secondary Content", name: "secondary_content", widget: "markdown"}
- name: "about"
  label: "About Page"
  files:
    - name: "about-data"
      label: "About"
      file: "data/about.yml"
      fields:
        - { label: "Main Content", name: "main_content", widget: "markdown" }
        - label: "Subteams"
          name: "subteams"
          widget: "list"
          fields:
            - {label: "Title", name: "title", widget: "string"}
            - {label: "Description", name: "description", widget: "markdown"}
            - {label: "Image", name: "image", widget: "image"}
- name: "games"
  label: "Games"
  files:
    - name: games-data
      label: "Games"
      file: "data/games.yml"
      fields:
        - label: Games
          name: games
          widget: list
          fields:
            - {label: "Title", name: "title", widget: "string"}
            - {label: "Description", name: "description", widget: "markdown"}
            - {label: "Year", name: "year", widget: "string"}
            - {label: "Alignment", name: "align", widget: "select", options: ["right", "left"]}
            - label: Banners
              name: banners
              widget: list
              fields:
                - {label: "Text", name: "text", widget: "string"}
- name: "partners_page"
  label: "Partners Page"
  files:
    - name: "partners-data-content"
      label: "Content"
      file: "data/Partners.yml"
      fields:
        - label: Title
          name: title
          widget: string
        - label: Body
          name: content
          widget: markdown
        - label: "Partner Levels"
          name: "Levels"
          widget: "list"
          fields:
            - {label: "Name", name: "name", widget: "string"}
            - {label: "Amount", name: "amount", widget: "string"}
        - label: "Testimonials"
          name: "testimonials"
          widget: "list"
          fields:
            - {label: "Name", name: "name", widget: "string"}
            - {label: "Grade", name: "grade", widget: "string"}
            - {label: "Testimonial", name: "testimonial", widget: "string"}
- name: "partners"
  label: "Partners List"
  files:
    - name: "partners-data"
      label: "Partners"
      file: "data/Partners.yml"
      fields:
        - label: "Partners List"
          name: "List"
          widget: "list"
          fields:
            - {label: "Name", name: "name", widget: "string"}
            - {label: "Location", name: "location", widget: "string"}
            - {label: "From", name: "from", widget: "string"}
            - {label: "URL", name: "url", widget: "string"}
            - {label: "Description", name: "desc", widget: "markdown"}
            - {label: "Level", name: "level", widget: "select", options: ["hurricane", "torrent", "thunderstorm", "zephyr", "breeze"]}
            - {label: "Logo", name: "logo", widget: "image"}
- name: "posts2019" # Used in routes, e.g., /admin/collections/blog
  label: "Posts 2019" # Used in the UI
  folder: "content/posts/2019" # The path to the folder where the documents are stored
  create: true # Allow users to create new documents in this collection
  slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
  fields: # The fields for each document, usually in front matter
    - {label: "Title", name: "title", widget: "string"}
    - {label: "Publish Date", name: "date", widget: "datetime"}
    - {label: "Body", name: "body", widget: "markdown"}
    - {label: "Seasons", name: "seasons", widget: "list"}
    - {label: "Image", name: "image", widget: "image"}
- name: "posts2018" # Used in routes, e.g., /admin/collections/blog
  label: "Posts 2018" # Used in the UI
  folder: "content/posts/2018" # The path to the folder where the documents are stored
  create: true # Allow users to create new documents in this collection
  slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
  fields: # The fields for each document, usually in front matter
    - {label: "Title", name: "title", widget: "string"}
    - {label: "Publish Date", name: "date", widget: "datetime"}
    - {label: "Body", name: "body", widget: "markdown"}
    - {label: "Seasons", name: "seasons", widget: "list"}
    - {label: "Image", name: "image", widget: "image"}
